import unittest
from unzip_scratch import unzip_scratch
import json
import sys
import os
from scratch_parser import scratch_parser

class TestScratchParser(unittest.TestCase):
        
    
    def setUp(self):
        
        self.scratch_unzipped = unzip_scratch()
        self.prog1 = json.loads(self.scratch_unzipped.unpack_sb3("files/test.sb3"))
        self.prog2 = json.loads(self.scratch_unzipped.unpack_sb3("files/stand_check2.sb3"))
        self.prog3 = json.loads(self.scratch_unzipped.unpack_sb3("files/stand_check.sb3"))
        self.prog4 = json.loads(self.scratch_unzipped.unpack_sb3("files/infinite_two_opcode.sb3"))
        self.prog5 = json.loads(self.scratch_unzipped.unpack_sb3("files/3l_opcode.sb3"))
        self.prog6 = json.loads(self.scratch_unzipped.unpack_sb3("files/complex4.sb3"))
        self.prog7 = json.loads(self.scratch_unzipped.unpack_sb3("files/complex3.sb3"))
        self.prog8 = json.loads(self.scratch_unzipped.unpack_sb3("files/complex2.sb3"))
        self.prog9 = json.loads(self.scratch_unzipped.unpack_sb3("files/complex.sb3"))
        self.file_name1 = os.path.basename("files/test.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name2 = os.path.basename("files/stand_check2.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name3 = os.path.basename("files/stand_check.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name4 = os.path.basename("files/infinite_two_opcode.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name5 = os.path.basename("files/3l_opcode.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name6 = os.path.basename("files/complex4.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name7 = os.path.basename("files/complex3.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name8 = os.path.basename("files/complex2.sb3").split('/')[-1].split('.sb3')[0]
        self.file_name9 = os.path.basename("files/complex.sb3").split('/')[-1].split('.sb3')[0]
        
        self.scratch_parser_inst = scratch_parser() 
        self.maxDiff = None
        return self.shortDescription()

    @unittest.skip("demonstrating skipping")  
    def test_scratch_nothing_onclick(self):
        
        expected2 = [
    "test",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "looks_sayforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "Hello!"
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ],
                [
                    "motion_movesteps",
                    [
                        [
                            "STEPS",
                            [
                                "10"
                            ]
                        ]
                    ]
                ],
                [
                    "control_repeat_until",
                    [
                        [
                            "BodyBlock",
                            [
                                "sensing_askandwait",
                                [
                                    [
                                        [
                                            "QUESTION",
                                            [
                                                "How old are you?"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ],
                        [
                            "CONDITION",
                            [
                                "operator_equals",
                                [
                                    [
                                        [
                                            "OPERAND1",
                                            [
                                                "sensing_answer",
                                                [
                                                    []
                                                ]
                                            ]
                                        ],
                                        [
                                            "OPERAND2",
                                            [
                                                "50"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_thinkforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "Hmm..."
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
        
        all_blocks_val = self.scratch_parser_inst.get_all_blocks_vals(self.prog1)
        
        parsed = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val,self.file_name1)
        
        
        self.assertEqual(expected2,parsed,msg="Test failed")

    @unittest.skip("demonstrating skipping")           
    def test_assertEq(self):
        expected = ['a',['b',['c','d']]]
        actual = ['a',['b',['c','d']]]
        not_actual = ['a',['b',['c','e']]]
        not_not_actual = ['a',['b',['c',['e']]]]
        self.assertEqual(expected,actual,msg="Test failed")
        self.assertNotEquals(expected,not_actual,msg="Test failed")
        self.assertNotEquals(not_not_actual,not_actual,msg="Test failed")

    @unittest.skip("demonstrating skipping")  
    def test_scratch_two_arg(self):
        expected_tree1 = [
    "stand_check",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "motion_movesteps",
                    [
                        [
                            "STEPS",
                            [
                                "10"
                            ]
                        ]
                    ]
                ],
                [
                    "motion_turnright",
                    [
                        [
                            "DEGREES",
                            [
                                "15"
                            ]
                        ]
                    ]
                ],
                [
                    "looks_sayforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "Hello!"
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
        expected_tree2 = [
    "stand_check2",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "looks_thinkforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "Hmm..."
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ],
                [
                    "motion_pointindirection",
                    [
                        [
                            "DIRECTION",
                            [
                                "90"
                            ]
                        ]
                    ]
                ],
                [
                    "motion_changexby",
                    [
                        [
                            "DX",
                            [
                                "10"
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
        

        all_blocks_val1 = self.scratch_parser_inst.get_all_blocks_vals(self.prog2)
        all_blocks_val2 = self.scratch_parser_inst.get_all_blocks_vals(self.prog3)
        parsed1 = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val1,self.file_name2)
        parsed2 = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val2,self.file_name3)
        

        self.assertEqual(expected_tree2,parsed1,msg="Test failed")
        self.assertEqual(expected_tree1,parsed2,msg="Test failed")

    @unittest.skip("demonstrating skipping")  
    def test_infinite_loop(self):
        expected = [
    "infinite_two_opcode",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "looks_sayforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "Infinite with two opcodes in the body"
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ],
                [
                    "control_repeat",
                    [
                        [
                            "TIMES",
                            [
                                "10"
                            ]
                        ],
                        [
                            "BodyBlock",
                            [
                                "looks_say",
                                [
                                    [
                                        [
                                            "MESSAGE",
                                            [
                                                "opcode1"
                                            ]
                                        ]
                                    ]
                                ],
                                "looks_think",
                                [
                                    [
                                        [
                                            "MESSAGE",
                                            [
                                                "opcode2"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
        
        all_blocks_val = self.scratch_parser_inst.get_all_blocks_vals(self.prog4)
        parsed = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val,self.file_name4)
        
        self.assertEqual(expected,parsed,msg="Test failed")
    
    @unittest.skip("demonstrating skipping")  
    def test_loop_in_a_loop_in_a_loop(self):
        expected = [
    "3l_opcode",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "looks_sayforsecs",
                    [
                        [
                            "MESSAGE",
                            [
                                "loop in a loop in a loop with 2 opcodes"
                            ]
                        ],
                        [
                            "SECS",
                            [
                                "2"
                            ]
                        ]
                    ]
                ],
                [
                    "control_repeat",
                    [
                        [
                            "TIMES",
                            [
                                "10"
                            ]
                        ],
                        [
                            "BodyBlock",
                            [
                                "control_repeat",
                                [
                                    [
                                        [
                                            "TIMES",
                                            [
                                                "10"
                                            ]
                                        ],
                                        [
                                            "BodyBlock",
                                            [
                                                "control_repeat",
                                                [
                                                    [
                                                        [
                                                            "TIMES",
                                                            [
                                                                "10"
                                                            ]
                                                        ],
                                                        [
                                                            "BodyBlock",
                                                            [
                                                                "motion_movesteps",
                                                                [
                                                                    [
                                                                        [
                                                                            "STEPS",
                                                                            [
                                                                                "10"
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ],
                                                                "sound_seteffectto",
                                                                [
                                                                    [
                                                                        [
                                                                            "VALUE",
                                                                            [
                                                                                "100"
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]
        
        all_blocks_val = self.scratch_parser_inst.get_all_blocks_vals(self.prog5)
        parsed = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val,self.file_name5)
        
        self.assertEqual(expected,parsed,msg="Test failed")

    
    def tearDown(self) :
        
        return self.shortDescription()
        
    @unittest.skip("demonstrating skipping")    
    def test_input_blocks(self):
        expected = [
                [
                    "SUBSTACK",
                    [
                        "sensing_askandwait",
                        [
                            [
                                [
                                    "QUESTION",
                                    [
                                        "How old are you?"
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "CONDITION",
                    [
                        "operator_equals",
                        [
                            [
                                [
                                    "OPERAND1",
                                    [
                                        "sensing_answer",
                                        [
                                            []
                                        ]
                                    ]
                                ],
                                [
                                    "OPERAND2",
                                    [
                                        "50"
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]

        all_blocks_val = self.scratch_parser_inst.get_all_blocks_vals(self.prog1)
        inp_block = self.scratch_parser_inst.read_input_values_by_id(all_blocks_val,"8J%l~hNqUpt0Lfv1;iR^")
        parsed_block  = self.scratch_parser_inst.correct_input_block_tree_by_id(all_blocks_val,inp_block,"8J%l~hNqUpt0Lfv1;iR^")
        self.assertEqual(expected,parsed_block,msg="Test failed")

    @unittest.skip("demonstrating skipping")  
    def test_input_specific_keys(self):
        expected = ['SECS', ['2']]
        all_blocks = self.scratch_parser_inst.get_all_blocks_vals(self.prog1)
        block_by_id_key = self.scratch_parser_inst.get_input_block_by_id_key(all_blocks,",r([,#`OV3[DwDfw/x./","SECS")
        self.assertEqual(expected,block_by_id_key,msg="Test failed")

    
    def test_get_total_edges(self):
        all_blocks = self.scratch_parser_inst.get_all_blocks_vals(self.prog1)
        parsed_tree = self.scratch_parser_inst.create_next_values2(all_blocks,self.file_name1)
        actual_edges = self.scratch_parser_inst.get_total_edges(parsed_tree)
        empty_tree = []
        non_list_input = 92
        tr_wt_sing_node = [1]
        self.assertEqual(13,actual_edges,msg="Test Failed")
        self.assertEqual(0,self.scratch_parser_inst.get_total_edges(empty_tree))
        self.assertEqual(0,self.scratch_parser_inst.get_total_edges(non_list_input))
        self.assertEqual(0,self.scratch_parser_inst.get_total_edges(tr_wt_sing_node))

    def test_get_total_nodes(self):
        all_blocks = self.scratch_parser_inst.get_all_blocks_vals(self.prog1)
        parsed_tree = self.scratch_parser_inst.create_next_values2_disp(all_blocks,self.file_name1)
        single_node = ["eventwhenclicked"]
        actual_nodes = self.scratch_parser_inst.get_total_nodes(parsed_tree,all_blocks)
        self.assertEqual(26,actual_nodes,msg="Test Failed")
        self.assertEqual(1,self.scratch_parser_inst.get_total_nodes(single_node,all_blocks),msg="Test Failed single node")


    @unittest.skip("demonstrating skipping")  
    def test_complex4(self):
        expected = [
    "complex4",
    [
        [
            "event_whenflagclicked",
            [
                [
                    "motion_movesteps",
                    [
                        [
                            "STEPS",
                            [
                                "operator_subtract",
                                [
                                    [
                                        [
                                            "NUM1",
                                            [
                                                "7"
                                            ]
                                        ],
                                        [
                                            "NUM2",
                                            [
                                                "5"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "motion_pointindirection",
                    [
                        [
                            "DIRECTION",
                            [
                                "90"
                            ]
                        ]
                    ]
                ],
                [
                    "motion_ifonedgebounce",
                    []
                ],
                [
                    "looks_say",
                    [
                        [
                            "MESSAGE",
                            [
                                "data_itemnumoflist",
                                [
                                    [
                                        [
                                            "ITEM",
                                            [
                                                "thing"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_changesizeby",
                    [
                        [
                            "CHANGE",
                            [
                                "sensing_of",
                                [
                                    [
                                        [
                                            "OBJECT",
                                            [
                                                "sensing_of_object_menu",
                                                [
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_hide",
                    []
                ],
                [
                    "sound_playuntildone",
                    [
                        [
                            "SOUND_MENU",
                            [
                                "sound_sounds_menu",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "sound_changevolumeby",
                    [
                        [
                            "VOLUME",
                            [
                                "sensing_mousex",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "control_repeat",
                    [
                        [
                            "TIMES",
                            [
                                "sensing_distanceto",
                                [
                                    [
                                        [
                                            "DISTANCETOMENU",
                                            [
                                                "sensing_distancetomenu",
                                                [
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ],
                        [
                            "BodyBlock",
                            [
                                "control_if",
                                [
                                    [
                                        [
                                            "CONDITION",
                                            [
                                                "sensing_mousedown",
                                                [
                                                    []
                                                ]
                                            ]
                                        ],
                                        [
                                            "ThenBranch",
                                            [
                                                "sensing_setdragmode",
                                                [
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                ],
                                "control_repeat_until",
                                [
                                    [
                                        [
                                            "CONDITION",
                                            [
                                                "operator_and",
                                                [
                                                    [
                                                        [
                                                            "OPERAND1",
                                                            [
                                                                "sensing_keypressed",
                                                                [
                                                                    [
                                                                        [
                                                                            "KEY_OPTION",
                                                                            [
                                                                                "sensing_keyoptions",
                                                                                [
                                                                                    []
                                                                                ]
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ]
                                                            ]
                                                        ],
                                                        [
                                                            "OPERAND2",
                                                            [
                                                                "sensing_mousedown",
                                                                [
                                                                    []
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ],
                                        [
                                            "BodyBlock",
                                            [
                                                "looks_think",
                                                [
                                                    [
                                                        [
                                                            "MESSAGE",
                                                            [
                                                                "operator_round",
                                                                [
                                                                    [
                                                                        [
                                                                            "NUM",
                                                                            [
                                                                                "operator_mod",
                                                                                [
                                                                                    [
                                                                                        [
                                                                                            "NUM1",
                                                                                            [
                                                                                                "8"
                                                                                            ]
                                                                                        ],
                                                                                        [
                                                                                            "NUM2",
                                                                                            [
                                                                                                "operator_mathop",
                                                                                                [
                                                                                                    [
                                                                                                        [
                                                                                                            "NUM",
                                                                                                            [
                                                                                                                "8"
                                                                                                            ]
                                                                                                        ]
                                                                                                    ]
                                                                                                ]
                                                                                            ]
                                                                                        ]
                                                                                    ]
                                                                                ]
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ],
                                                "data_insertatlist",
                                                [
                                                    [
                                                        [
                                                            "ITEM",
                                                            [
                                                                "thing"
                                                            ]
                                                        ],
                                                        [
                                                            "INDEX",
                                                            [
                                                                "1"
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "control_stop",
                    []
                ]
            ]
        ],
        [
            "event_whenkeypressed",
            [
                "KEY_OPTION_space",
                [
                    [
                        "motion_turnright",
                        [
                            [
                                "DEGREES",
                                [
                                    "operator_random",
                                    [
                                        [
                                            [
                                                "FROM",
                                                [
                                                    "data_lengthoflist",
                                                    [
                                                        []
                                                    ]
                                                ]
                                            ],
                                            [
                                                "TO",
                                                [
                                                    "10"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "motion_pointtowards",
                        [
                            [
                                "TOWARDS",
                                [
                                    "motion_pointtowards_menu",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "motion_setrotationstyle",
                        []
                    ],
                    [
                        "looks_thinkforsecs",
                        [
                            [
                                "MESSAGE",
                                [
                                    "sensing_current",
                                    [
                                        []
                                    ]
                                ]
                            ],
                            [
                                "SECS",
                                [
                                    "2"
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_setsizeto",
                        [
                            [
                                "SIZE",
                                [
                                    "100"
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_gotofrontback",
                        []
                    ],
                    [
                        "sound_play",
                        [
                            [
                                "SOUND_MENU",
                                [
                                    "sound_sounds_menu",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "sound_setvolumeto",
                        [
                            [
                                "VOLUME",
                                [
                                    "sensing_mousey",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "control_forever",
                        [
                            [
                                "BodyBlock",
                                [
                                    "sensing_askandwait",
                                    [
                                        [
                                            [
                                                "QUESTION",
                                                [
                                                    "data_itemoflist",
                                                    [
                                                        [
                                                            [
                                                                "INDEX",
                                                                [
                                                                    "1"
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ],
                                    "control_wait_until",
                                    [
                                        [
                                            [
                                                "CONDITION",
                                                [
                                                    "operator_or",
                                                    [
                                                        [
                                                            [
                                                                "OPERAND1",
                                                                [
                                                                    "sensing_mousedown",
                                                                    [
                                                                        []
                                                                    ]
                                                                ]
                                                            ],
                                                            [
                                                                "OPERAND2",
                                                                [
                                                                    "sensing_keypressed",
                                                                    [
                                                                        [
                                                                            [
                                                                                "KEY_OPTION",
                                                                                [
                                                                                    "sensing_keyoptions",
                                                                                    [
                                                                                        []
                                                                                    ]
                                                                                ]
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "data_replaceitemoflist",
                        [
                            [
                                "INDEX",
                                [
                                    "1"
                                ]
                            ],
                            [
                                "ITEM",
                                [
                                    "thing"
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            "event_whenthisspriteclicked",
            [
                [
                    "motion_turnleft",
                    [
                        [
                            "DEGREES",
                            [
                                "sensing_dayssince2000",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "motion_changexby",
                    [
                        [
                            "DX",
                            [
                                "motion_xposition",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_switchcostumeto",
                    [
                        [
                            "COSTUME",
                            [
                                "looks_costume",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_changeeffectby",
                    [
                        [
                            "CHANGE",
                            [
                                "sensing_answer",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "looks_goforwardbackwardlayers",
                    [
                        [
                            "NUM",
                            [
                                "sound_volume",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "sound_stopallsounds",
                    []
                ],
                [
                    "control_if",
                    [
                        [
                            "ThenBranch",
                            [
                                "control_delete_this_clone",
                                [
                                    []
                                ]
                            ]
                        ],
                        [
                            "CONDITION",
                            [
                                "sensing_keypressed",
                                [
                                    [
                                        [
                                            "KEY_OPTION",
                                            [
                                                "sensing_keyoptions",
                                                [
                                                    []
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "control_if",
                    [
                        [
                            "CONDITION",
                            [
                                "operator_not",
                                [
                                    [
                                        [
                                            "OPERAND",
                                            [
                                                "sensing_keypressed",
                                                [
                                                    [
                                                        [
                                                            "KEY_OPTION",
                                                            [
                                                                "sensing_keyoptions",
                                                                [
                                                                    []
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ],
                        [
                            "ThenBranch",
                            [
                                "data_setvariableto",
                                [
                                    [
                                        [
                                            "VALUE",
                                            [
                                                "80"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            "event_whenbackdropswitchesto",
            [
                "BACKDROP_backdrop1",
                [
                    [
                        "motion_goto",
                        [
                            [
                                "TO",
                                [
                                    "motion_goto_menu",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "motion_setx",
                        [
                            [
                                "X",
                                [
                                    "motion_yposition",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_nextcostume",
                        []
                    ],
                    [
                        "looks_seteffectto",
                        [
                            [
                                "VALUE",
                                [
                                    "looks_costumenumbername",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "sound_changeeffectby",
                        [
                            [
                                "VALUE",
                                [
                                    "sensing_loudness",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "event_broadcast",
                        [
                            [
                                "BROADCAST_INPUT",
                                [
                                    "message1"
                                ]
                            ]
                        ]
                    ],
                    [
                        "control_if_else",
                        [
                            [
                                "CONDITION",
                                [
                                    "sensing_touchingobject",
                                    [
                                        [
                                            [
                                                "TOUCHINGOBJECTMENU",
                                                [
                                                    "sensing_touchingobjectmenu",
                                                    [
                                                        []
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "ThenBranch",
                                [
                                    "control_if",
                                    [
                                        [
                                            [
                                                "CONDITION",
                                                [
                                                    "operator_gt",
                                                    [
                                                        [
                                                            [
                                                                "OPERAND1",
                                                                [
                                                                    "operator_join",
                                                                    [
                                                                        [
                                                                            [
                                                                                "STRING1",
                                                                                [
                                                                                    "apple "
                                                                                ]
                                                                            ],
                                                                            [
                                                                                "STRING2",
                                                                                [
                                                                                    "banana"
                                                                                ]
                                                                            ]
                                                                        ]
                                                                    ]
                                                                ]
                                                            ],
                                                            [
                                                                "OPERAND2",
                                                                [
                                                                    "50"
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ],
                                            [
                                                "ThenBranch",
                                                [
                                                    "data_showvariable",
                                                    [
                                                        []
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "BodyBlock",
                                [
                                    "data_addtolist",
                                    [
                                        [
                                            [
                                                "ITEM",
                                                [
                                                    "thing"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "control_if",
                        [
                            [
                                "CONDITION",
                                [
                                    "data_listcontainsitem",
                                    [
                                        [
                                            [
                                                "ITEM",
                                                [
                                                    "thing"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "ThenBranch",
                                [
                                    "data_showlist",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            "event_whengreaterthan",
            [
                "WHENGREATERTHANMENU_LOUDNESS_VALUE_10",
                [
                    [
                        "motion_gotoxy",
                        [
                            [
                                "X",
                                [
                                    "sensing_username",
                                    [
                                        []
                                    ]
                                ]
                            ],
                            [
                                "Y",
                                [
                                    "looks_backdropnumbername",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "motion_changeyby",
                        [
                            [
                                "DY",
                                [
                                    "motion_direction",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_switchbackdropto",
                        [
                            [
                                "BACKDROP",
                                [
                                    "looks_backdrops",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_cleargraphiceffects",
                        []
                    ],
                    [
                        "sound_seteffectto",
                        [
                            [
                                "VALUE",
                                [
                                    "sensing_timer",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "event_broadcastandwait",
                        [
                            [
                                "BROADCAST_INPUT",
                                [
                                    "message1"
                                ]
                            ]
                        ]
                    ],
                    [
                        "control_wait_until",
                        [
                            [
                                "CONDITION",
                                [
                                    "sensing_touchingcolor",
                                    [
                                        [
                                            [
                                                "COLOR",
                                                [
                                                    "#6ebfd3"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "control_repeat_until",
                        [
                            [
                                "CONDITION",
                                [
                                    "operator_lt",
                                    [
                                        [
                                            [
                                                "OPERAND1",
                                                [
                                                    "operator_letter_of",
                                                    [
                                                        [
                                                            [
                                                                "LETTER",
                                                                [
                                                                    "1"
                                                                ]
                                                            ],
                                                            [
                                                                "STRING",
                                                                [
                                                                    "apple"
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ],
                                            [
                                                "OPERAND2",
                                                [
                                                    "50"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "BodyBlock",
                                [
                                    "data_hidevariable",
                                    [
                                        []
                                    ],
                                    "data_deleteoflist",
                                    [
                                        [
                                            [
                                                "INDEX",
                                                [
                                                    "1"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "data_hidelist",
                        []
                    ]
                ]
            ]
        ],
        [
            "event_whenbroadcastreceived",
            [
                "BROADCAST_OPTION_message1_RXM:nTYGHS$G+0JOV9MF",
                [
                    [
                        "motion_glideto",
                        [
                            [
                                "SECS",
                                [
                                    "1"
                                ]
                            ],
                            [
                                "TO",
                                [
                                    "motion_glideto_menu",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "motion_sety",
                        [
                            [
                                "Y",
                                [
                                    "looks_size",
                                    [
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_sayforsecs",
                        [
                            [
                                "MESSAGE",
                                [
                                    "operator_add",
                                    [
                                        [
                                            [
                                                "NUM1",
                                                [
                                                    "7"
                                                ]
                                            ],
                                            [
                                                "NUM2",
                                                [
                                                    "8"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "SECS",
                                [
                                    "2"
                                ]
                            ]
                        ]
                    ],
                    [
                        "looks_nextbackdrop",
                        []
                    ],
                    [
                        "looks_show",
                        []
                    ],
                    [
                        "control_repeat_until",
                        [
                            [
                                "BodyBlock",
                                [
                                    "sound_cleareffects",
                                    [
                                        []
                                    ],
                                    "control_wait",
                                    [
                                        [
                                            [
                                                "DURATION",
                                                [
                                                    "1"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            [
                                "CONDITION",
                                [
                                    "sensing_coloristouchingcolor",
                                    [
                                        [
                                            [
                                                "COLOR",
                                                [
                                                    "#6a1ed8"
                                                ]
                                            ],
                                            [
                                                "COLOR2",
                                                [
                                                    "#5cb11b"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        "sensing_resettimer",
                        []
                    ],
                    [
                        "data_deletealloflist",
                        []
                    ],
                    [
                        "control_wait_until",
                        [
                            [
                                "CONDITION",
                                [
                                    "operator_equals",
                                    [
                                        [
                                            [
                                                "OPERAND1",
                                                [
                                                    "operator_length",
                                                    [
                                                        [
                                                            [
                                                                "STRING",
                                                                [
                                                                    "apple"
                                                                ]
                                                            ]
                                                        ]
                                                    ]
                                                ]
                                            ],
                                            [
                                                "OPERAND2",
                                                [
                                                    "50"
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            "control_start_as_clone",
            [
                [
                    "control_create_clone_of",
                    [
                        [
                            "CLONE_OPTION",
                            [
                                "control_create_clone_of_menu",
                                [
                                    []
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "control_if",
                    [
                        [
                            "CONDITION",
                            [
                                "operator_contains",
                                [
                                    [
                                        [
                                            "STRING1",
                                            [
                                                "apple"
                                            ]
                                        ],
                                        [
                                            "STRING2",
                                            [
                                                "a"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ],
                        [
                            "ThenBranch",
                            [
                                "data_changevariableby",
                                [
                                    [
                                        [
                                            "VALUE",
                                            [
                                                "1"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
            "procedures_definition",
            [
                [
                    [
                        "procedures_prototype",
                        [
                            [
                                "comp4block_comp4"
                            ],
                            [
                                "argument_reporter_string_number",
                                [
                                    "VALUE_number"
                                ]
                            ],
                            [
                                "argument_reporter_boolean",
                                [
                                    "VALUE_true"
                                ]
                            ]
                        ]
                    ],
                    [
                        "procedures_call",
                        [
                            [
                                "6psEeyKNwbAq9?cPG_c#",
                                [
                                    "looks_backdropnumbername",
                                    [
                                        []
                                    ]
                                ]
                            ],
                            [
                                "3.Xk%pjRv/P67n];n9b;",
                                [
                                    "sensing_touchingobject",
                                    [
                                        [
                                            [
                                                "TOUCHINGOBJECTMENU",
                                                [
                                                    "sensing_touchingobjectmenu",
                                                    [
                                                        []
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]  
        
        all_blocks_val = self.scratch_parser_inst.get_all_blocks_vals(self.prog6)
        parsed = self.scratch_parser_inst.create_next_values2_disp(all_blocks_val,self.file_name6)
        self.assertEqual(expected,parsed,msg="Test failed")

if __name__ == '__main__':
    unittest.main()
    
